# Generated by Django 5.1.6 on 2025-06-02 20:21

import django.contrib.postgres.fields
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('workouts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AnamnesisModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_nascimento', models.DateField(blank=True, null=True)),
                ('profissao', models.CharField(blank=True, max_length=255, null=True)),
                ('nomeDoResponsavel', models.CharField(blank=True, max_length=255, null=True)),
                ('contatoDoResponsavel', models.CharField(blank=True, max_length=255, null=True)),
                ('peso', models.FloatField(default=0.0)),
                ('altura', models.FloatField(default=0.0)),
                ('participaDeExtensao', models.BooleanField(default=False)),
                ('praticaAtividade', models.BooleanField(default=False)),
                ('boxSensacoes', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=50), blank=True, default=list, size=None)),
                ('fazDieta', models.BooleanField(default=False)),
                ('quantasRefeicoes', models.IntegerField(blank=True, null=True)),
                ('horasDeSono', models.IntegerField(blank=True, null=True)),
                ('litrosDeAgua', models.FloatField(blank=True, null=True)),
                ('bebe', models.BooleanField(default=False)),
                ('fuma', models.BooleanField(default=False)),
                ('temColesterolAlto', models.BooleanField(default=False)),
                ('hdl', models.CharField(blank=True, max_length=20, null=True)),
                ('ldl', models.CharField(blank=True, max_length=20, null=True)),
                ('temTrigliceridesAlto', models.BooleanField(default=False)),
                ('diabetico', models.BooleanField(default=False)),
                ('tipoDeDiabete', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=10), blank=True, default=list, size=None)),
                ('descDiabete', models.TextField(blank=True, null=True)),
                ('hipertenso', models.BooleanField(default=False)),
                ('descHipertenso', models.TextField(blank=True, null=True)),
                ('asma', models.BooleanField(default=False)),
                ('descAsma', models.TextField(blank=True, null=True)),
                ('temProblemasRespiratorios', models.BooleanField(default=False)),
                ('descProblemasRespiratorios', models.TextField(blank=True, null=True)),
                ('paisObesos', models.BooleanField(default=False)),
                ('jaFezCirurgia', models.BooleanField(default=False)),
                ('descCirurgia', models.TextField(blank=True, null=True)),
                ('usaMedicamento', models.BooleanField(default=False)),
                ('descMedicamento', models.TextField(blank=True, null=True)),
                ('recomendacaoMedica', models.BooleanField(default=False)),
                ('descDesconforto', models.TextField(blank=True, null=True)),
                ('descRestricaoMedica', models.TextField(blank=True, null=True)),
                ('objetivos', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=50), blank=True, default=list, size=None)),
                ('descOutro', models.TextField(blank=True, null=True)),
                ('problemaDeCoracao', models.BooleanField(default=False)),
                ('doresNoPeito', models.BooleanField(default=False)),
                ('doresNoPeitoEmAtividade', models.BooleanField(default=False)),
                ('desequilibrio', models.BooleanField(default=False)),
                ('problemaOsseo', models.BooleanField(default=False)),
                ('medicamentoParaPressao', models.BooleanField(default=False)),
                ('outrasRazoes', models.BooleanField(default=False)),
                ('descOutrasRazoes', models.TextField(blank=True, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='anamnesis', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='BloodPressureModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('pre_workout', models.IntegerField()),
                ('post_workout', models.IntegerField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blood_pressure', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CognitiveGameSessionModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('correct_answers', models.IntegerField()),
                ('incorrect_answers', models.IntegerField()),
                ('total_time', models.FloatField(help_text='Tempo total da sessão em segundos')),
                ('fastest_response', models.FloatField()),
                ('slowest_response', models.FloatField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='GlycemiaModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('pre_workout', models.IntegerField()),
                ('post_workout', models.IntegerField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='glycemia', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='HealthControlModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('insonia', models.IntegerField(blank=True, default=0, null=True)),
                ('ansiedade', models.IntegerField(blank=True, default=0, null=True)),
                ('estresse', models.IntegerField(blank=True, default=0, null=True)),
                ('falta_de_motivacao', models.IntegerField(blank=True, default=0, null=True)),
                ('dificuldade_de_concentracao', models.IntegerField(blank=True, default=0, null=True)),
                ('tristeza_frequente', models.IntegerField(blank=True, default=0, null=True)),
                ('enxaqueca', models.IntegerField(blank=True, default=0, null=True)),
                ('tonturas', models.IntegerField(blank=True, default=0, null=True)),
                ('problemas_de_visao', models.IntegerField(blank=True, default=0, null=True)),
                ('zumbido_no_ouvido', models.IntegerField(blank=True, default=0, null=True)),
                ('dores_nos_olhos', models.IntegerField(blank=True, default=0, null=True)),
                ('dor_no_ombro', models.IntegerField(blank=True, default=0, null=True)),
                ('dor_nas_costas', models.IntegerField(blank=True, default=0, null=True)),
                ('dor_nos_joelhos', models.IntegerField(blank=True, default=0, null=True)),
                ('caibras', models.IntegerField(blank=True, default=0, null=True)),
                ('fraqueza', models.IntegerField(blank=True, default=0, null=True)),
                ('dores_articulares', models.IntegerField(blank=True, default=0, null=True)),
                ('inchaco', models.IntegerField(blank=True, default=0, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SelfAssessmentModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('effort', models.IntegerField()),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='WaterConsumeModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('water_goal', models.IntegerField()),
                ('water_consumed', models.IntegerField()),
                ('isAchieved', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='water_consume', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='DailyRecordModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(db_index=True, default=django.utils.timezone.now)),
                ('rate', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='workouts.workoutratemodel')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_record', to=settings.AUTH_USER_MODEL)),
                ('workout', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='workouts.workout')),
                ('effort', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='health.selfassessmentmodel')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('user', 'date'), name='unique_daily_record_per_day')],
            },
        ),
    ]
