# Generated by Django 5.1.6 on 2025-07-03 03:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('health', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailyrecordmodel',
            name='blood_pressure',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='health.bloodpressuremodel'),
        ),
        migrations.AddField(
            model_name='dailyrecordmodel',
            name='glycemia',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='health.glycemiamodel'),
        ),
    ]
