# Generated by Django 5.1.6 on 2025-06-23 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_user_password_reset_otp_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(error_messages={'unique': 'Um usuário com este nome já existe.'}, help_text='Obrigatório. 150 caracteres ou menos. Apenas letras e espaços são permitidos.', max_length=150, unique=True),
        ),
    ]
